stages:
  - build
  - check

default:
  before_script:
    - rustc --version
    - cargo --version

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

rustfmt:
  stage: check
  image: rust:latest
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check
  allow_failure: true

clippy:
  stage: check
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -- -D warnings
